name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: |
            dev-requirements.txt
            fluent.syntax/setup.py
            fluent.runtime/setup.py
      - run: python -m pip install -r dev-requirements.txt
      - run: python -m pip install ./fluent.syntax ./fluent.runtime
      - run: python -m flake8
      - run: python -m mypy fluent.syntax/fluent fluent.runtime/fluent
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11, 3.12, pypy3.9, pypy3.10]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            fluent.syntax/setup.py
            fluent.runtime/setup.py
      - run: python -m pip install ./fluent.syntax ./fluent.runtime
      - run: python -m unittest discover -s fluent.syntax
      - run: python -m unittest discover -s fluent.runtime

  # Test compatibility with the oldest Python version we claim to support,
  # and for fluent.runtime's compatibility with a range of fluent.syntax versions.
  compatibility:
    runs-on: ubuntu-20.04 # https://github.com/actions/setup-python/issues/544
    strategy:
      matrix:
        fluent-syntax:
          - ./fluent.syntax
          - fluent.syntax==0.19.0
          - fluent.syntax==0.18.1 six
          - fluent.syntax==0.17.0 six
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - run: python -m pip install ${{ matrix.fluent-syntax }}
      - run: python -m pip install ./fluent.runtime
      - run: python -m unittest discover -s fluent.runtime
